version: "3.9"

services:
  web:
    build: .
    container_name: homework03_app
    ports:
      - "3000:3000" # Local port 3000 â†’ container 3000
    volumes:
      - ./storage:/app/storage # Store data.json outside the container
    restart: unless-stopped
